import Mathlib.Analysis.Complex.Exponential
import Mathlib.Algebra.Algebra.Hom.Rat
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.RingTheory.AlgebraicIndependent.Transcendental
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis

/-!
# Schanuel's conjecture

This file formalizes the standard finite-family statement of Schanuel's conjecture.
The conjecture itself remains open, so it is deliberately recorded as a `Prop` rather than
postulated, and no theorem is given an unproved placeholder.

We prove several pieces of honest progress around the statement:

* the dimension-zero case;
* the conjectured bound whenever either the coordinates or their exponentials are already
  algebraically independent;
* the unconditional upper bound `trdeg ≤ 2n` and monotonicity under taking subfamilies;
* an exact characterization of the one-dimensional bound, and its equivalence with the
  Hermite--Lindemann theorem.

`Schanuel.Structural` gives an equivalent finite-selection form of the conjecture, while
`Schanuel.LindemannAttempt` connects the one-dimensional case to Mathlib's existing analytic
Lindemann estimate and isolates the missing arithmetic step.
-/

namespace Schanuel

open Function Set

noncomputable section

/-- The `2n` complex numbers `z₁, ..., zₙ, exp z₁, ..., exp zₙ`, as one family. -/
def expPair {n : ℕ} (z : Fin n → ℂ) : Fin n ⊕ Fin n → ℂ :=
  Sum.elim z (fun i ↦ Complex.exp (z i))

/-- The set of coordinates and their exponentials. -/
def generators {n : ℕ} (z : Fin n → ℂ) : Set ℂ :=
  Set.range z ∪ Set.range (fun i ↦ Complex.exp (z i))

theorem range_expPair {n : ℕ} (z : Fin n → ℂ) :
    Set.range (expPair z) = generators z := by
  exact Set.Sum.elim_range _ _

/-- The subfield `ℚ(z₁, ..., zₙ, exp z₁, ..., exp zₙ)` of `ℂ`. -/
def generatedField {n : ℕ} (z : Fin n → ℂ) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ (generators z)

/-- The transcendence-degree inequality predicted by Schanuel for a particular family. -/
def Bound {n : ℕ} (z : Fin n → ℂ) : Prop :=
  Cardinal.mk (Fin n) ≤ Algebra.trdeg ℚ (generatedField z)

/-- The standard finite-family form of Schanuel's conjecture. -/
def Conjecture : Prop :=
  ∀ (n : ℕ) (z : Fin n → ℂ), LinearIndependent ℚ z → Bound z

/-- For a linearly independent `n`-tuple, the span appearing in the usual informal statement
really has rational dimension `n`. -/
theorem finrank_span_range_eq {n : ℕ} {z : Fin n → ℂ} (hz : LinearIndependent ℚ z) :
    Module.finrank ℚ (Submodule.span ℚ (Set.range z)) = n := by
  simpa using finrank_span_eq_card hz

/-- A coordinate, regarded as an element of the field generated by all coordinates and
their exponentials. -/
def coordinate {n : ℕ} (z : Fin n → ℂ) (i : Fin n) : generatedField z :=
  ⟨z i, IntermediateField.subset_adjoin ℚ _ (Or.inl ⟨i, rfl⟩)⟩

/-- An exponential, regarded as an element of the field generated by the coordinates and
their exponentials. -/
def exponential {n : ℕ} (z : Fin n → ℂ) (i : Fin n) : generatedField z :=
  ⟨Complex.exp (z i), IntermediateField.subset_adjoin ℚ _ (Or.inr ⟨i, rfl⟩)⟩

@[simp]
theorem coe_coordinate {n : ℕ} (z : Fin n → ℂ) (i : Fin n) :
    (coordinate z i : ℂ) = z i :=
  rfl

@[simp]
theorem coe_exponential {n : ℕ} (z : Fin n → ℂ) (i : Fin n) :
    (exponential z i : ℂ) = Complex.exp (z i) :=
  rfl

/-- All `2n` displayed generators, regarded as elements of their generated field. -/
def liftedExpPair {n : ℕ} (z : Fin n → ℂ) :
    Fin n ⊕ Fin n → generatedField z :=
  fun i ↦ ⟨expPair z i, IntermediateField.subset_adjoin ℚ _ <| by
    rw [← range_expPair]
    exact Set.mem_range_self i⟩

@[simp]
theorem coe_liftedExpPair {n : ℕ} (z : Fin n → ℂ) (i : Fin n ⊕ Fin n) :
    (liftedExpPair z i : ℂ) = expPair z i :=
  rfl

theorem image_val_range_liftedExpPair {n : ℕ} (z : Fin n → ℂ) :
    Subtype.val '' Set.range (liftedExpPair z) = Set.range (expPair z) := by
  ext x
  simp only [Set.mem_image, Set.mem_range]
  constructor
  · rintro ⟨y, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨liftedExpPair z i, ⟨i, rfl⟩, rfl⟩

/-- The inclusion into `ℂ`, using its canonical rational algebra structure. -/
def inclusion {n : ℕ} (z : Fin n → ℂ) : generatedField z →ₐ[ℚ] ℂ :=
  (generatedField z).val.toRingHom.toRatAlgHom

@[simp]
theorem inclusion_apply {n : ℕ} (z : Fin n → ℂ) (x : generatedField z) :
    inclusion z x = (x : ℂ) := by
  simp [inclusion]

theorem fieldRange_inclusion {n : ℕ} (z : Fin n → ℂ) :
    (inclusion z).fieldRange = generatedField z := by
  ext x
  simp [AlgHom.mem_fieldRange]

theorem adjoin_range_liftedExpPair_eq_top {n : ℕ} (z : Fin n → ℂ) :
    IntermediateField.adjoin ℚ (Set.range (liftedExpPair z)) = ⊤ := by
  apply IntermediateField.map_injective (inclusion z)
  rw [IntermediateField.adjoin_map, ← AlgHom.fieldRange_eq_map]
  rw [show inclusion z '' Set.range (liftedExpPair z) =
      Subtype.val '' Set.range (liftedExpPair z) by rfl]
  rw [image_val_range_liftedExpPair, range_expPair, fieldRange_inclusion]
  rfl

open scoped IntermediateField.algebraAdjoinAdjoin in
theorem isAlgebraic_adjoin_range_liftedExpPair {n : ℕ} (z : Fin n → ℂ) :
    Algebra.IsAlgebraic
      (Algebra.adjoin ℚ (Set.range (liftedExpPair z))) (generatedField z) := by
  let f :
      IntermediateField.adjoin ℚ (Set.range (liftedExpPair z)) →ₐ[
        Algebra.adjoin ℚ (Set.range (liftedExpPair z))] generatedField z :=
    IsScalarTower.toAlgHom _ _ _
  have hf_surj : Function.Surjective f := by
    intro x
    refine ⟨⟨x, ?_⟩, rfl⟩
    rw [adjoin_range_liftedExpPair_eq_top]
    exact IntermediateField.mem_top
  let e := AlgEquiv.ofBijective f ⟨f.injective, hf_surj⟩
  exact e.isAlgebraic

theorem trdeg_le_cardinalMk_sum {n : ℕ} (z : Fin n → ℂ) :
    Algebra.trdeg ℚ (generatedField z) ≤ Cardinal.mk (Fin n ⊕ Fin n) := by
  letI : Algebra.IsAlgebraic
      (Algebra.adjoin ℚ (Set.range (liftedExpPair z))) (generatedField z) :=
    isAlgebraic_adjoin_range_liftedExpPair z
  exact (Algebra.IsAlgebraic.trdeg_le_cardinalMk
    ℚ (Set.range (liftedExpPair z))).trans Cardinal.mk_range_le

/-- The unconditional upper bound: at most `2n` displayed generators can contribute to the
transcendence degree. -/
theorem trdeg_le_two_mul {n : ℕ} (z : Fin n → ℂ) :
    Algebra.trdeg ℚ (generatedField z) ≤ ((2 * n : ℕ) : Cardinal) := by
  calc
    Algebra.trdeg ℚ (generatedField z) ≤ Cardinal.mk (Fin n ⊕ Fin n) :=
      trdeg_le_cardinalMk_sum z
    _ = ((2 * n : ℕ) : Cardinal) := by simp [two_mul]

theorem generatedField_mono {m n : ℕ} {w : Fin m → ℂ} {z : Fin n → ℂ}
    (h : generators w ⊆ generators z) : generatedField w ≤ generatedField z := by
  exact IntermediateField.adjoin.mono ℚ _ _ h

/-- Inclusion of generated fields, packaged with the canonical rational-algebra instances. -/
def generatedFieldInclusion {m n : ℕ} {w : Fin m → ℂ} {z : Fin n → ℂ}
    (h : generators w ⊆ generators z) : generatedField w →ₐ[ℚ] generatedField z :=
  (IntermediateField.inclusion (generatedField_mono h)).toRingHom.toRatAlgHom

theorem trdeg_mono {m n : ℕ} {w : Fin m → ℂ} {z : Fin n → ℂ}
    (h : generators w ⊆ generators z) :
    Algebra.trdeg ℚ (generatedField w) ≤ Algebra.trdeg ℚ (generatedField z) := by
  exact trdeg_le_of_injective (generatedFieldInclusion h)
    (IntermediateField.inclusion_injective (generatedField_mono h))

theorem generators_comp_subset {m n : ℕ} (z : Fin n → ℂ) (f : Fin m → Fin n) :
    generators (z ∘ f) ⊆ generators z := by
  rintro x (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · exact Or.inl ⟨f i, rfl⟩
  · exact Or.inr ⟨f i, rfl⟩

/-- Reindexing by any map can only shrink the generated field's transcendence degree. -/
theorem trdeg_comp_le {m n : ℕ} (z : Fin n → ℂ) (f : Fin m → Fin n) :
    Algebra.trdeg ℚ (generatedField (z ∘ f)) ≤
      Algebra.trdeg ℚ (generatedField z) :=
  trdeg_mono (generators_comp_subset z f)

/-- Reindexing by an equivalence preserves the generated transcendence degree. -/
theorem trdeg_comp_equiv {m n : ℕ} (z : Fin n → ℂ) (e : Fin m ≃ Fin n) :
    Algebra.trdeg ℚ (generatedField (z ∘ e)) =
      Algebra.trdeg ℚ (generatedField z) := by
  apply le_antisymm (trdeg_comp_le z e)
  have h := trdeg_comp_le (z ∘ e) e.symm
  have he : (z ∘ e) ∘ e.symm = z := by
    funext i
    simp
  rw [he] at h
  exact h

/-- The generated field always has finite transcendence degree. -/
theorem trdeg_lt_aleph0 {n : ℕ} (z : Fin n → ℂ) :
    Algebra.trdeg ℚ (generatedField z) < Cardinal.aleph0 :=
  (trdeg_le_two_mul z).trans_lt Cardinal.natCast_lt_aleph0

theorem Conjecture.lower_bound (hC : Conjecture) {n : ℕ} {z : Fin n → ℂ}
    (hz : LinearIndependent ℚ z) :
    ((n : ℕ) : Cardinal) ≤ Algebra.trdeg ℚ (generatedField z) := by
  simpa [Conjecture, Bound] using hC n z hz

/-- Under Schanuel, the transcendence degree lies in its expected finite interval. -/
theorem Conjecture.lower_and_upper (hC : Conjecture) {n : ℕ} {z : Fin n → ℂ}
    (hz : LinearIndependent ℚ z) :
    ((n : ℕ) : Cardinal) ≤ Algebra.trdeg ℚ (generatedField z) ∧
      Algebra.trdeg ℚ (generatedField z) ≤ ((2 * n : ℕ) : Cardinal) :=
  ⟨hC.lower_bound hz, trdeg_le_two_mul z⟩

theorem Conjecture.generatedField_transcendental
    (hC : Conjecture) {n : ℕ} {z : Fin n → ℂ}
    (hn : 0 < n) (hz : LinearIndependent ℚ z) :
    Algebra.Transcendental ℚ (generatedField z) := by
  rw [← trdeg_ne_zero_iff]
  have hn' : (0 : Cardinal) < ((n : ℕ) : Cardinal) := by simpa using hn
  exact (hn'.trans_le (hC.lower_bound hz)).ne'

/-- Applying the conjecture to a linearly independent subfamily gives a lower bound inside the
field generated by the full family. -/
theorem Conjecture.subfamily_lower_bound
    (hC : Conjecture) {m n : ℕ} {z : Fin n → ℂ}
    (hz : LinearIndependent ℚ z) (f : Fin m ↪ Fin n) :
    Cardinal.mk (Fin m) ≤ Algebra.trdeg ℚ (generatedField z) := by
  have hsub : LinearIndependent ℚ (z ∘ f) := hz.comp f f.injective
  have hbound := hC m (z ∘ f) hsub
  change Cardinal.mk (Fin m) ≤ Algebra.trdeg ℚ (generatedField (z ∘ f)) at hbound
  exact hbound.trans (trdeg_comp_le z f)

theorem algebraicIndependent_coordinate {n : ℕ} {z : Fin n → ℂ}
    (hz : AlgebraicIndependent ℚ z) :
    AlgebraicIndependent ℚ (coordinate z) := by
  apply AlgebraicIndependent.of_comp (generatedField z).val
  simpa [coordinate, Function.comp_def] using hz

theorem algebraicIndependent_exponential {n : ℕ} {z : Fin n → ℂ}
    (hz : AlgebraicIndependent ℚ (fun i ↦ Complex.exp (z i))) :
    AlgebraicIndependent ℚ (exponential z) := by
  apply AlgebraicIndependent.of_comp (generatedField z).val
  simpa [exponential, Function.comp_def] using hz

/-- Algebraic independence of the coordinates is a sufficient (much stronger) hypothesis
for Schanuel's predicted bound. -/
theorem bound_of_algebraicIndependent_coordinate {n : ℕ} {z : Fin n → ℂ}
    (hz : AlgebraicIndependent ℚ z) : Bound z := by
  exact (algebraicIndependent_coordinate hz).cardinalMk_le_trdeg

/-- Algebraic independence of all exponentials is also sufficient for Schanuel's bound. -/
theorem bound_of_algebraicIndependent_exponential {n : ℕ} {z : Fin n → ℂ}
    (hz : AlgebraicIndependent ℚ (fun i ↦ Complex.exp (z i))) : Bound z := by
  exact (algebraicIndependent_exponential hz).cardinalMk_le_trdeg

theorem bound_of_algebraicIndependent_either {n : ℕ} {z : Fin n → ℂ}
    (h : AlgebraicIndependent ℚ z ∨
      AlgebraicIndependent ℚ (fun i ↦ Complex.exp (z i))) : Bound z := by
  rcases h with hz | hexp
  · exact bound_of_algebraicIndependent_coordinate hz
  · exact bound_of_algebraicIndependent_exponential hexp

/-- Schanuel's bound is unconditional for the empty family. -/
theorem bound_zero (z : Fin 0 → ℂ) : Bound z := by
  simp [Bound]

/-- A named one-element family, used to expose the one-dimensional boundary. -/
def singletonFamily (z : ℂ) : Fin 1 → ℂ :=
  fun _ ↦ z

theorem bound_singleton_of_transcendental {z : ℂ} (hz : Transcendental ℚ z) :
    Bound (singletonFamily z) := by
  apply bound_of_algebraicIndependent_coordinate
  rw [algebraicIndependent_unique_type_iff]
  simpa [singletonFamily] using hz

theorem bound_singleton_of_exp_transcendental {z : ℂ}
    (hz : Transcendental ℚ (Complex.exp z)) : Bound (singletonFamily z) := by
  apply bound_of_algebraicIndependent_exponential
  rw [algebraicIndependent_unique_type_iff]
  simpa [singletonFamily] using hz

/-- For one generator, the transcendence-degree bound says exactly that at least one of
`z` and `exp z` is transcendental. -/
theorem bound_singleton_iff_transcendental_or_exp (z : ℂ) :
    Bound (singletonFamily z) ↔
      Transcendental ℚ z ∨ Transcendental ℚ (Complex.exp z) := by
  constructor
  · intro hbound
    by_cases hz : Transcendental ℚ z
    · exact Or.inl hz
    by_cases hexp : Transcendental ℚ (Complex.exp z)
    · exact Or.inr hexp
    exfalso
    letI : Algebra.IsAlgebraic ℚ (generatedField (singletonFamily z)) := by
      apply IntermediateField.isAlgebraic_adjoin
      intro x hx
      rw [generators] at hx
      rcases hx with ⟨i, rfl⟩ | ⟨i, rfl⟩
      · simpa [singletonFamily] using (not_not.mp hz).isIntegral
      · simpa [singletonFamily] using (not_not.mp hexp).isIntegral
    have htrdeg : Algebra.trdeg ℚ (generatedField (singletonFamily z)) = 0 :=
      trdeg_eq_zero
    simp [Bound, htrdeg] at hbound
  · rintro (hz | hexp)
    · exact bound_singleton_of_transcendental hz
    · exact bound_singleton_of_exp_transcendental hexp

/-- The classical Hermite--Lindemann statement needed for the remaining branch of the
one-dimensional argument. Mathlib 4.29.1 contains analytic infrastructure toward this theorem,
but not the finished theorem, so we keep it as an explicit hypothesis. -/
def HermiteLindemannStatement : Prop :=
  ∀ z : ℂ, IsAlgebraic ℚ z → z ≠ 0 → Transcendental ℚ (Complex.exp z)

/-- The restriction of Schanuel's conjecture to one-element families. -/
def OneDimensionalConjecture : Prop :=
  ∀ z : ℂ, LinearIndependent ℚ (singletonFamily z) → Bound (singletonFamily z)

/-- Hermite--Lindemann implies the one-dimensional case of Schanuel's conjecture. -/
theorem hermiteLindemann_implies_bound_singleton
    (hHL : HermiteLindemannStatement) (z : ℂ)
    (hz : LinearIndependent ℚ (singletonFamily z)) : Bound (singletonFamily z) := by
  have hz0 : z ≠ 0 := by
    rw [linearIndependent_unique_iff] at hz
    simpa [singletonFamily] using hz
  by_cases hzt : Transcendental ℚ z
  · exact bound_singleton_of_transcendental hzt
  · exact bound_singleton_of_exp_transcendental (hHL z (not_not.mp hzt) hz0)

/-- The one-dimensional case of Schanuel's conjecture is exactly Hermite--Lindemann. -/
theorem oneDimensionalConjecture_iff_hermiteLindemann :
    OneDimensionalConjecture ↔ HermiteLindemannStatement := by
  constructor
  · intro hS z hzAlg hz0
    have hzLI : LinearIndependent ℚ (singletonFamily z) := by
      rw [linearIndependent_unique_iff]
      simpa [singletonFamily] using hz0
    have hEither :=
      (bound_singleton_iff_transcendental_or_exp z).mp (hS z hzLI)
    exact hEither.resolve_left (fun hzTrans ↦ hzTrans hzAlg)
  · intro hHL z hzLI
    exact hermiteLindemann_implies_bound_singleton hHL z hzLI

/-- In particular, the full conjecture specializes to Hermite--Lindemann. -/
theorem conjecture_implies_hermiteLindemann
    (hS : Conjecture) : HermiteLindemannStatement := by
  apply oneDimensionalConjecture_iff_hermiteLindemann.mp
  intro z hzLI
  exact hS 1 (singletonFamily z) hzLI

end

end Schanuel
