import Schanuel.Structural

/-!
# The boundary where all exponential values are algebraic

If every `exp (z i)` is algebraic, adjoining the exponential half of the Schanuel family does
not change transcendence degree.  Consequently the predicted bound is exactly algebraic
independence of the input coordinates.  This is a field-theoretic reduction, not a proof of that
algebraic independence.
-/

namespace Schanuel

open Set

noncomputable section

open scoped IntermediateField.algebraAdjoinAdjoin in
/-- When all displayed exponential values are algebraic, the Schanuel field is algebraic over
the algebra generated by the coordinates alone. -/
theorem isAlgebraic_adjoin_coordinate_of_exponential_isAlgebraic
    {n : ℕ} (z : Fin n → ℂ)
    (hexp : ∀ i, IsAlgebraic ℚ (Complex.exp (z i))) :
    Algebra.IsAlgebraic
      (Algebra.adjoin ℚ (Set.range (coordinate z))) (generatedField z) := by
  let B := Algebra.adjoin ℚ (Set.range (coordinate z))
  letI : Algebra.IsAlgebraic
      (Algebra.adjoin ℚ (Set.range (liftedExpPair z))) (generatedField z) :=
    isAlgebraic_adjoin_range_liftedExpPair z
  change Algebra.IsAlgebraic B (generatedField z)
  constructor
  intro x
  apply (Algebra.IsAlgebraic.isAlgebraic
    (R := Algebra.adjoin ℚ (Set.range (liftedExpPair z))) x).adjoin_of_forall_isAlgebraic
  intro u hu
  rcases hu.1 with ⟨i, rfl⟩
  rcases i with i | i
  · exact False.elim (hu.2 ⟨i, rfl⟩)
  · have he : IsAlgebraic ℚ (exponential z i) := by
      apply (isAlgebraic_algHom_iff (inclusion z) (inclusion z).injective).mp
      simpa [exponential] using hexp i
    exact he.extendScalars
      (algebraMap ℚ (Algebra.adjoin ℚ (Set.range (coordinate z)))).injective

/-- In the all-algebraic-exponential boundary, Schanuel's bound is exactly algebraic
independence of the logarithm coordinates. -/
theorem bound_iff_algebraicIndependent_coordinate_of_exponential_isAlgebraic
    {n : ℕ} (z : Fin n → ℂ)
    (hexp : ∀ i, IsAlgebraic ℚ (Complex.exp (z i))) :
    Bound z ↔ AlgebraicIndependent ℚ z := by
  constructor
  · intro hbound
    letI : Algebra.IsAlgebraic
        (Algebra.adjoin ℚ (Set.range (coordinate z))) (generatedField z) :=
      isAlgebraic_adjoin_coordinate_of_exponential_isAlgebraic z hexp
    have htb : IsTranscendenceBasis ℚ (coordinate z) :=
      Algebra.IsAlgebraic.isTranscendenceBasis_of_le_trdeg_of_finite
        ℚ (coordinate z) hbound
    have hcomplex := htb.1.map' (generatedField z).val.injective
    simpa [coordinate, Function.comp_def] using hcomplex
  · exact bound_of_algebraicIndependent_coordinate

/-- The full conjecture would force algebraic independence of every rationally independent
family of logarithms of algebraic numbers. -/
theorem conjecture_implies_algebraicIndependent_of_exponential_isAlgebraic
    (hS : Conjecture) {n : ℕ} (z : Fin n → ℂ) (hlin : LinearIndependent ℚ z)
    (hexp : ∀ i, IsAlgebraic ℚ (Complex.exp (z i))) :
    AlgebraicIndependent ℚ z := by
  apply (bound_iff_algebraicIndependent_coordinate_of_exponential_isAlgebraic z hexp).mp
  exact hS n z hlin

end

end Schanuel
