import Schanuel.ControlledMultipliers

/-!
# Controlled multipliers as rational matrices

A scalar preserving the rational span of a finite family acts on that span by a rational
matrix.  Choosing coordinates row by row gives a concrete matrix whose transformed family is
the coordinatewise product by the scalar.  The denominator-clearing theorem for rational
matrices then makes every corresponding exponential integral over the original generated
field.
-/

namespace Schanuel

open Function Set

noncomputable section

/-- The controlled multipliers of a rational subspace form a rational subalgebra of `ℂ`. -/
def controlledMultiplierAlgebra (Z : Submodule ℚ ℂ) : Subalgebra ℚ ℂ where
  carrier := {a | ∀ x, x ∈ Z → a * x ∈ Z}
  add_mem' ha hb x hx := by
    simpa [add_mul] using Z.add_mem (ha x hx) (hb x hx)
  mul_mem' ha hb x hx := by
    rw [mul_assoc]
    exact ha _ (hb x hx)
  algebraMap_mem' q x hx := by
    change (q : ℂ) * x ∈ Z
    rw [← Rat.smul_def]
    exact Z.smul_mem q hx

@[simp]
theorem mem_controlledMultiplierAlgebra {Z : Submodule ℚ ℂ} {a : ℂ} :
    a ∈ controlledMultiplierAlgebra Z ↔ a ∈ controlledMultipliers Z :=
  Iff.rfl

@[simp]
theorem controlledMultiplierAlgebra_toSubmodule (Z : Submodule ℚ ℂ) :
    (controlledMultiplierAlgebra Z).toSubmodule = controlledMultipliers Z := by
  ext a
  rfl

/-- A chosen rational matrix representing multiplication by `a` on the coordinates `z`.

The definition is noncomputable only because coordinates in a finite spanning family are
chosen; no linear-independence hypothesis on `z` is needed.
-/
def controlledMultiplierMatrix {n : ℕ} (z : Fin n → ℂ)
    (a : controlledMultipliers (Submodule.span ℚ (Set.range z))) :
    Matrix (Fin n) (Fin n) ℚ :=
  fun i ↦ Classical.choose <|
    (Submodule.mem_span_range_iff_exists_fun ℚ).mp <|
      a.property (z i) (Submodule.subset_span (Set.mem_range_self i))

/-- The chosen matrix represents multiplication by the controlled scalar, row by row. -/
theorem controlledMultiplierMatrix_spec {n : ℕ} (z : Fin n → ℂ)
    (a : controlledMultipliers (Submodule.span ℚ (Set.range z))) (i : Fin n) :
    (a : ℂ) * z i = ∑ j, controlledMultiplierMatrix z a i j • z j := by
  exact (Classical.choose_spec
    ((Submodule.mem_span_range_iff_exists_fun ℚ).mp
      (a.property (z i) (Submodule.subset_span (Set.mem_range_self i))))).symm

/-- Multiplication by a scalar preserving the rational span is a rational matrix operation. -/
theorem exists_rationalMatrix_mul_eq_of_mem_controlledMultipliers {n : ℕ}
    (z : Fin n → ℂ) (a : ℂ)
    (ha : a ∈ controlledMultipliers (Submodule.span ℚ (Set.range z))) :
    ∃ B : Matrix (Fin n) (Fin n) ℚ,
      ∀ i, a * z i = ∑ j, B i j • z j := by
  let a' : controlledMultipliers (Submodule.span ℚ (Set.range z)) := ⟨a, ha⟩
  exact ⟨controlledMultiplierMatrix z a', controlledMultiplierMatrix_spec z a'⟩

/-- The exponential of a controlled multiple of any coordinate is integral over the field
generated by the original coordinates and their exponentials. -/
theorem exp_mul_isIntegral_of_mem_controlledMultipliers {n : ℕ}
    (z : Fin n → ℂ) (a : ℂ)
    (ha : a ∈ controlledMultipliers (Submodule.span ℚ (Set.range z))) (i : Fin n) :
    IsIntegral (generatedField z) (Complex.exp (a * z i)) := by
  let a' : controlledMultipliers (Submodule.span ℚ (Set.range z)) := ⟨a, ha⟩
  exact exp_mul_isIntegral_of_rational_combinations z a
    (controlledMultiplierMatrix z a') (controlledMultiplierMatrix_spec z a') i

/-- Algebraic form of `exp_mul_isIntegral_of_mem_controlledMultipliers`. -/
theorem exp_mul_isAlgebraic_of_mem_controlledMultipliers {n : ℕ}
    (z : Fin n → ℂ) (a : ℂ)
    (ha : a ∈ controlledMultipliers (Submodule.span ℚ (Set.range z))) (i : Fin n) :
    IsAlgebraic (generatedField z) (Complex.exp (a * z i)) :=
  (exp_mul_isIntegral_of_mem_controlledMultipliers z a ha i).isAlgebraic

end

end Schanuel
