import Schanuel
import Mathlib.RingTheory.Algebraic.Integral

/-!
# Integer shears of exponential families

Adding integral multiples of one distinguished coordinate to the other coordinates is a
unipotent rational change of basis.  Because the complex exponential turns integral multiples
into integral powers, this operation preserves the field generated by the coordinates and their
exponentials, not merely its transcendence degree.

The simultaneous operation below packages the finite collection of commuting elementary shears
with a common pivot.  The condition `k j = 0` says that the pivot itself is left fixed.
-/

namespace Schanuel

open Function Set

noncomputable section

/-- Add the integral multiple `k i` of the pivot `z j` to coordinate `i`. -/
def integerShearFamily {n : ℕ} (z : Fin n → ℂ) (j : Fin n) (k : Fin n → ℤ) :
    Fin n → ℂ :=
  fun i ↦ z i + (k i : ℂ) * z j

@[simp]
theorem integerShearFamily_apply {n : ℕ} (z : Fin n → ℂ) (j : Fin n)
    (k : Fin n → ℤ) (i : Fin n) :
    integerShearFamily z j k i = z i + (k i : ℂ) * z j :=
  rfl

@[simp]
theorem integerShearFamily_pivot {n : ℕ} (z : Fin n → ℂ) (j : Fin n)
    (k : Fin n → ℤ) (hk : k j = 0) :
    integerShearFamily z j k j = z j := by
  simp [integerShearFamily, hk]

/-- Negating every coefficient reverses a shear family whose pivot coefficient is zero. -/
theorem integerShearFamily_neg_cancel {n : ℕ} (z : Fin n → ℂ) (j : Fin n)
    (k : Fin n → ℤ) (hk : k j = 0) :
    integerShearFamily (integerShearFamily z j k) j (fun i ↦ -k i) = z := by
  funext i
  simp [integerShearFamily, hk]

/-- A shear family with a fixed pivot preserves rational linear independence. -/
theorem linearIndependent_integerShearFamily_iff {n : ℕ} (z : Fin n → ℂ)
    (j : Fin n) (k : Fin n → ℤ) (hk : k j = 0) :
    LinearIndependent ℚ (integerShearFamily z j k) ↔ LinearIndependent ℚ z := by
  let c : Fin n → ℚ := fun i ↦ (k i : ℚ)
  have hc : c j = 0 := by simp [c, hk]
  have hfamily : integerShearFamily z j k = z + (c · • z j) := by
    funext i
    simp only [integerShearFamily, Pi.add_apply, c]
    rw [Rat.smul_def, Rat.cast_intCast]
  rw [hfamily]
  exact linearIndependent_add_smul_iff hc

/-- Every generator after an integral shear belongs to the original generated field. -/
theorem generatedField_integerShearFamily_le {n : ℕ} (z : Fin n → ℂ)
    (j : Fin n) (k : Fin n → ℤ) :
    generatedField (integerShearFamily z j k) ≤ generatedField z := by
  rw [generatedField, IntermediateField.adjoin_le_iff]
  rintro x (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · exact (generatedField z).add_mem
      (IntermediateField.subset_adjoin ℚ _ (Or.inl ⟨i, rfl⟩))
      ((generatedField z).mul_mem
        (IntermediateField.intCast_mem _ (k i))
        (IntermediateField.subset_adjoin ℚ _ (Or.inl ⟨j, rfl⟩)))
  · change Complex.exp (integerShearFamily z j k i) ∈ generatedField z
    rw [integerShearFamily_apply, Complex.exp_add]
    apply (generatedField z).mul_mem
      (IntermediateField.subset_adjoin ℚ _ (Or.inr ⟨i, rfl⟩))
    rw [Complex.exp_int_mul]
    exact (generatedField z).pow_mem
      (IntermediateField.subset_adjoin ℚ _ (Or.inr ⟨j, rfl⟩)) (k i)

/-- An integral shear family with fixed pivot preserves the generated field exactly. -/
theorem generatedField_integerShearFamily_eq {n : ℕ} (z : Fin n → ℂ)
    (j : Fin n) (k : Fin n → ℤ) (hk : k j = 0) :
    generatedField (integerShearFamily z j k) = generatedField z := by
  apply le_antisymm (generatedField_integerShearFamily_le z j k)
  have h := generatedField_integerShearFamily_le
    (integerShearFamily z j k) j (fun i ↦ -k i)
  rw [integerShearFamily_neg_cancel z j k hk] at h
  exact h

/-- The elementary shear adding `k * z j` only to coordinate `i`. -/
def integerShear {n : ℕ} (z : Fin n → ℂ) (i j : Fin n) (k : ℤ) : Fin n → ℂ :=
  integerShearFamily z j (fun l ↦ if l = i then k else 0)

@[simp]
theorem integerShear_apply_same {n : ℕ} (z : Fin n → ℂ) (i j : Fin n) (k : ℤ) :
    integerShear z i j k i = z i + (k : ℂ) * z j := by
  simp [integerShear]

@[simp]
theorem integerShear_apply_of_ne {n : ℕ} (z : Fin n → ℂ) (i j l : Fin n) (k : ℤ)
    (hl : l ≠ i) :
    integerShear z i j k l = z l := by
  simp [integerShear, hl]

/-- An elementary shear between distinct coordinates preserves rational linear independence. -/
theorem linearIndependent_integerShear_iff {n : ℕ} (z : Fin n → ℂ)
    (i j : Fin n) (k : ℤ) (hij : i ≠ j) :
    LinearIndependent ℚ (integerShear z i j k) ↔ LinearIndependent ℚ z := by
  apply linearIndependent_integerShearFamily_iff
  simp [hij.symm]

/-- An elementary shear between distinct coordinates preserves the generated field exactly. -/
theorem generatedField_integerShear_eq {n : ℕ} (z : Fin n → ℂ)
    (i j : Fin n) (k : ℤ) (hij : i ≠ j) :
    generatedField (integerShear z i j k) = generatedField z := by
  apply generatedField_integerShearFamily_eq
  simp [hij.symm]

/-- The elementary shear with coefficient `-k` is the inverse of the shear with coefficient
`k`. -/
theorem integerShear_neg_cancel {n : ℕ} (z : Fin n → ℂ)
    (i j : Fin n) (k : ℤ) (hij : i ≠ j) :
    integerShear (integerShear z i j k) i j (-k) = z := by
  change integerShearFamily
    (integerShearFamily z j (fun l ↦ if l = i then k else 0)) j
      (fun l ↦ if l = i then -k else 0) = z
  convert integerShearFamily_neg_cancel z j
    (fun l ↦ if l = i then k else 0) (by simp [hij.symm]) using 1
  funext l
  by_cases hli : l = i
  · simp [hli]
  · simp [hli]

/-- Adding an algebraic number to a transcendental number stays transcendental. -/
theorem transcendental_add_of_isAlgebraic_left {a t : ℂ}
    (ha : IsAlgebraic ℚ a) (ht : Transcendental ℚ t) :
    Transcendental ℚ (a + t) := by
  intro hat
  apply ht
  have hsub : IsIntegral ℚ ((a + t) - a) :=
    (isAlgebraic_iff_isIntegral.mp hat).sub (isAlgebraic_iff_isIntegral.mp ha)
  simpa using hsub.isAlgebraic

/-- Coefficients which add the pivot exactly to the algebraic coordinates. -/
def algebraicEliminationCoeffs {n : ℕ} (z : Fin n → ℂ) : Fin n → ℤ :=
  fun i ↦ @ite ℤ (IsAlgebraic ℚ (z i)) (Classical.propDecidable _) 1 0

/-- Shear all algebraic coordinates by a chosen transcendental pivot. -/
def transcendentalShear {n : ℕ} (z : Fin n → ℂ) (j : Fin n) : Fin n → ℂ :=
  integerShearFamily z j (algebraicEliminationCoeffs z)

theorem algebraicEliminationCoeffs_pivot_eq_zero {n : ℕ} {z : Fin n → ℂ}
    {j : Fin n} (hj : Transcendental ℚ (z j)) :
    algebraicEliminationCoeffs z j = 0 := by
  rw [algebraicEliminationCoeffs, if_neg]
  exact hj

/-- If the pivot is transcendental, every coordinate after the selected shear is
transcendental. -/
theorem transcendental_transcendentalShear {n : ℕ} {z : Fin n → ℂ} {j : Fin n}
    (hj : Transcendental ℚ (z j)) :
    ∀ i, Transcendental ℚ (transcendentalShear z j i) := by
  intro i
  by_cases hi : IsAlgebraic ℚ (z i)
  · rw [transcendentalShear, integerShearFamily_apply,
      algebraicEliminationCoeffs, if_pos hi]
    simpa using transcendental_add_of_isAlgebraic_left hi hj
  · rw [transcendentalShear, integerShearFamily_apply,
      algebraicEliminationCoeffs, if_neg hi]
    simpa using (show Transcendental ℚ (z i) from hi)

theorem linearIndependent_transcendentalShear_iff {n : ℕ} {z : Fin n → ℂ} {j : Fin n}
    (hj : Transcendental ℚ (z j)) :
    LinearIndependent ℚ (transcendentalShear z j) ↔ LinearIndependent ℚ z := by
  exact linearIndependent_integerShearFamily_iff z j _
    (algebraicEliminationCoeffs_pivot_eq_zero hj)

theorem generatedField_transcendentalShear_eq {n : ℕ} {z : Fin n → ℂ} {j : Fin n}
    (hj : Transcendental ℚ (z j)) :
    generatedField (transcendentalShear z j) = generatedField z := by
  exact generatedField_integerShearFamily_eq z j _
    (algebraicEliminationCoeffs_pivot_eq_zero hj)

theorem bound_transcendentalShear_iff {n : ℕ} {z : Fin n → ℂ} {j : Fin n}
    (hj : Transcendental ℚ (z j)) :
    Bound (transcendentalShear z j) ↔ Bound z := by
  unfold Bound
  have htrdeg :
      Algebra.trdeg ℚ (generatedField (transcendentalShear z j)) =
        Algebra.trdeg ℚ (generatedField z) :=
    (IntermediateField.equivOfEq
      (generatedField_transcendentalShear_eq hj)).trdeg_eq
  rw [htrdeg]

/-- A linearly independent family containing one transcendental coordinate admits a finite
simultaneous integer shear with the same generated field and with every coordinate
transcendental. -/
theorem exists_all_transcendental_integerShear {n : ℕ} {z : Fin n → ℂ}
    (hz : LinearIndependent ℚ z) (htrans : ∃ j, Transcendental ℚ (z j)) :
    ∃ w : Fin n → ℂ,
      LinearIndependent ℚ w ∧ generatedField w = generatedField z ∧
        ∀ i, Transcendental ℚ (w i) := by
  obtain ⟨j, hj⟩ := htrans
  exact ⟨transcendentalShear z j,
    (linearIndependent_transcendentalShear_iff hj).2 hz,
    generatedField_transcendentalShear_eq hj,
    transcendental_transcendentalShear hj⟩

/-- Structural dichotomy for arbitrary linearly independent tuples: either all coordinates are
algebraic, or a finite collection of commuting elementary integer shears produces an
all-transcendental tuple with exactly the same generated field. -/
theorem all_algebraic_or_exists_all_transcendental_integerShear {n : ℕ} {z : Fin n → ℂ}
    (hz : LinearIndependent ℚ z) :
    (∀ i, IsAlgebraic ℚ (z i)) ∨
      ∃ w : Fin n → ℂ,
        LinearIndependent ℚ w ∧ generatedField w = generatedField z ∧
          ∀ i, Transcendental ℚ (w i) := by
  classical
  by_cases h : ∀ i, IsAlgebraic ℚ (z i)
  · exact Or.inl h
  · apply Or.inr
    apply exists_all_transcendental_integerShear hz
    simpa only [Transcendental] using not_forall.mp h

end

end Schanuel
