import Schanuel.Structural
import Schanuel.GaloisStableAnalytic2

/-!
# The first iterated-exponential boundary

For a nonzero algebraic number `a`, Hermite--Lindemann makes `exp a` transcendental and hence
the pair `(a, exp a)` rationally linearly independent.  The two-dimensional Schanuel bound for
this pair is nevertheless exactly the algebraic independence of `exp a` and `exp (exp a)`.

This is the first mixed case not covered by the finite-Galois stable-relation argument: one of
the exponents in a prospective relation is already transcendental.
-/

namespace Schanuel

open Set

noncomputable section

/-- The first iterated-exponential family `(a, exp a)`. -/
def iteratedExpFamily (a : ℂ) : Fin 2 → ℂ :=
  ![a, Complex.exp a]

@[simp]
theorem iteratedExpFamily_zero (a : ℂ) : iteratedExpFamily a 0 = a := rfl

@[simp]
theorem iteratedExpFamily_one (a : ℂ) :
    iteratedExpFamily a 1 = Complex.exp a := rfl

/-- Hermite--Lindemann already proves the rational linear independence needed to apply the
two-dimensional Schanuel conjecture to `(a, exp a)`. -/
theorem linearIndependent_iteratedExpFamily
    {a : ℂ} (ha : IsAlgebraic ℚ a) (ha0 : a ≠ 0) :
    LinearIndependent ℚ (iteratedExpFamily a) := by
  have hexp : Transcendental ℚ (Complex.exp a) :=
    LindemannAttempt.hermiteLindemann_of_galoisStableEndpoint a ha ha0
  change LinearIndependent ℚ ![a, Complex.exp a]
  rw [LinearIndependent.pair_iff' ha0]
  intro q hq
  apply hexp
  rw [← hq]
  simpa [Algebra.smul_def] using
    (isAlgebraic_algebraMap (A := ℂ) q).mul ha

/-- For the family `(a, exp a)`, where `a` is algebraic, the full generated field is algebraic
over the algebra generated by its two displayed exponentials.  Indeed `a` is algebraic and the
other coordinate `exp a` is itself the first displayed exponential. -/
theorem isAlgebraic_adjoin_exponential_iteratedExpFamily
    {a : ℂ} (ha : IsAlgebraic ℚ a) :
    Algebra.IsAlgebraic
      (Algebra.adjoin ℚ (Set.range (exponential (iteratedExpFamily a))))
      (generatedField (iteratedExpFamily a)) := by
  let z := iteratedExpFamily a
  let B := Algebra.adjoin ℚ (Set.range (exponential z))
  letI : Algebra.IsAlgebraic
      (Algebra.adjoin ℚ (Set.range (liftedExpPair z))) (generatedField z) :=
    isAlgebraic_adjoin_range_liftedExpPair z
  change Algebra.IsAlgebraic B (generatedField z)
  constructor
  intro x
  apply (Algebra.IsAlgebraic.isAlgebraic
    (R := Algebra.adjoin ℚ (Set.range (liftedExpPair z))) x).adjoin_of_forall_isAlgebraic
  intro u hu
  rcases hu.1 with ⟨i, rfl⟩
  rcases i with i | i
  · fin_cases i
    · have hcoord : IsAlgebraic ℚ (coordinate z 0) := by
        apply (isAlgebraic_algHom_iff (inclusion z) (inclusion z).injective).mp
        simpa [z] using ha
      exact hcoord.extendScalars
        (algebraMap ℚ (Algebra.adjoin ℚ (Set.range (exponential z)))).injective
    · exact isAlgebraic_algebraMap
        (⟨exponential z 0, Algebra.subset_adjoin ⟨0, rfl⟩⟩ : B)
  · exact False.elim (hu.2 ⟨i, rfl⟩)

/-- The Schanuel bound for `(a, exp a)` says exactly that `exp a` and `exp (exp a)` are
algebraically independent. -/
theorem bound_iteratedExpFamily_iff_algebraicIndependent
    {a : ℂ} (ha : IsAlgebraic ℚ a) :
    Bound (iteratedExpFamily a) ↔
      AlgebraicIndependent ℚ ![Complex.exp a, Complex.exp (Complex.exp a)] := by
  let z := iteratedExpFamily a
  have hvalues : (fun i ↦ Complex.exp (z i)) =
      ![Complex.exp a, Complex.exp (Complex.exp a)] := by
    funext i
    fin_cases i <;> rfl
  constructor
  · intro hbound
    letI : Algebra.IsAlgebraic
        (Algebra.adjoin ℚ (Set.range (exponential z))) (generatedField z) :=
      isAlgebraic_adjoin_exponential_iteratedExpFamily ha
    have htb : IsTranscendenceBasis ℚ (exponential z) :=
      Algebra.IsAlgebraic.isTranscendenceBasis_of_le_trdeg_of_finite
        ℚ (exponential z) hbound
    have hcomplex : AlgebraicIndependent ℚ (fun i ↦ Complex.exp (z i)) := by
      simpa [exponential] using htb.1.map' (generatedField z).val.injective
    simpa only [hvalues] using hcomplex
  · intro h
    apply bound_of_algebraicIndependent_exponential
    change AlgebraicIndependent ℚ (fun i ↦ Complex.exp (z i))
    rw [hvalues]
    exact h

/-- The full conjecture specializes, for every nonzero algebraic `a`, to algebraic independence
of the first two iterated exponential values. -/
theorem conjecture_implies_algebraicIndependent_iteratedExp
    (hS : Conjecture) {a : ℂ} (ha : IsAlgebraic ℚ a) (ha0 : a ≠ 0) :
    AlgebraicIndependent ℚ ![Complex.exp a, Complex.exp (Complex.exp a)] := by
  apply (bound_iteratedExpFamily_iff_algebraicIndependent ha).mp
  exact hS 2 (iteratedExpFamily a) (linearIndependent_iteratedExpFamily ha ha0)

end

end Schanuel
