import Schanuel.AlgebraicInputs
import Schanuel.Structural
import Mathlib.Analysis.SpecialFunctions.Log.Basic

/-!
# A sharp two-dimensional mixed obstruction

The family `(log 2, log 2 + 1)` is rationally linearly independent, but its Schanuel field is
exactly `Q(log 2, exp 1)`.  Thus even this elementary mixed family asks for the algebraic
independence of `log 2` and `e`; the theorem for algebraic input families does not supply the
missing relative independence.
-/

namespace Schanuel.MixedObstruction

open Complex Set

noncomputable section

/-- The complex number obtained from the real logarithm of `2`. -/
def logTwo : ℂ := (Real.log 2 : ℝ)

/-- The simplest genuinely mixed two-dimensional family. -/
def family : Fin 2 → ℂ := ![logTwo, logTwo + 1]

/-- The two generators left after the elementary exponential identities are used. -/
def core : Fin 2 → ℂ := ![logTwo, Complex.exp 1]

@[simp]
theorem exp_logTwo : Complex.exp logTwo = 2 := by
  change Complex.exp ((Real.log 2 : ℝ) : ℂ) = 2
  rw [← Complex.ofReal_exp, Real.exp_log (by norm_num : (0 : ℝ) < 2)]
  norm_num

theorem logTwo_ne_zero : logTwo ≠ 0 := by
  change ((Real.log 2 : ℝ) : ℂ) ≠ 0
  exact Complex.ofReal_ne_zero.mpr
    (Real.log_pos (by norm_num : (1 : ℝ) < 2)).ne'

/-- `log 2` is transcendental, as an immediate consequence of the checked
Hermite--Lindemann endpoint. -/
theorem logTwo_transcendental : Transcendental ℚ logTwo := by
  intro hlog
  have h := Schanuel.LindemannAttempt.hermiteLindemann_of_galoisStableEndpoint
    logTwo hlog logTwo_ne_zero
  apply h
  rw [exp_logTwo]
  exact isAlgebraic_algebraMap (A := ℂ) (2 : ℚ)

@[simp]
theorem family_zero : family 0 = logTwo := rfl

@[simp]
theorem family_one : family 1 = logTwo + 1 := rfl

@[simp]
theorem core_zero : core 0 = logTwo := rfl

@[simp]
theorem core_one : core 1 = Complex.exp 1 := rfl

@[simp]
theorem exp_family_zero : Complex.exp (family 0) = 2 := by
  exact exp_logTwo

@[simp]
theorem exp_family_one : Complex.exp (family 1) = 2 * Complex.exp 1 := by
  rw [family_one, Complex.exp_add, exp_logTwo]

/-- The mixed family really satisfies Schanuel's rational linear-independence hypothesis. -/
theorem family_linearIndependent : LinearIndependent ℚ family := by
  rw [linearIndependent_fin2]
  constructor
  · intro hzero
    apply logTwo_transcendental
    have hlog : logTwo = -1 := by
      rw [family_one] at hzero
      exact eq_neg_of_add_eq_zero_left hzero
    rw [hlog]
    simpa using (isAlgebraic_algebraMap (A := ℂ) (-1 : ℚ))
  · intro a ha
    apply logTwo_transcendental
    have ha1 : a ≠ 1 := by
      intro haone
      subst a
      simp [family] at ha
    have hlog : logTwo = algebraMap ℚ ℂ (-a / (a - 1)) := by
      rw [family_one] at ha
      change (a : ℂ) * (logTwo + 1) = logTwo at ha
      change logTwo = ((-a / (a - 1) : ℚ) : ℂ)
      push_cast
      apply (eq_div_iff (by exact_mod_cast sub_ne_zero.mpr ha1)).mpr
      linear_combination ha
    rw [hlog]
    exact isAlgebraic_algebraMap (A := ℂ) (-a / (a - 1))

/-- The field generated by the mixed family and its exponentials is exactly
`Q(log 2, e)`. -/
theorem generatedField_eq_adjoin_core :
    generatedField family = IntermediateField.adjoin ℚ (Set.range core) := by
  apply le_antisymm
  · apply IntermediateField.adjoin_le_iff.mpr
    rintro x (hx | hx)
    · obtain ⟨i, rfl⟩ := hx
      fin_cases i
      · exact IntermediateField.subset_adjoin ℚ _ ⟨0, rfl⟩
      · have hone : (1 : ℂ) ∈ IntermediateField.adjoin ℚ (Set.range core) := by
          simp
        exact (IntermediateField.adjoin ℚ (Set.range core)).add_mem
          (IntermediateField.subset_adjoin ℚ _ ⟨0, rfl⟩) hone
    · obtain ⟨i, rfl⟩ := hx
      fin_cases i
      · simp [family]
      · simpa [family, Complex.exp_add, exp_logTwo] using
          (IntermediateField.adjoin ℚ (Set.range core)).mul_mem
          (IntermediateField.algebraMap_mem _ (2 : ℚ))
          (IntermediateField.subset_adjoin ℚ _ ⟨1, rfl⟩)
  · apply IntermediateField.adjoin_le_iff.mpr
    rintro x ⟨i, rfl⟩
    fin_cases i
    · exact IntermediateField.subset_adjoin ℚ _ (Or.inl ⟨0, rfl⟩)
    · have hnum : 2 * Complex.exp 1 ∈ generatedField family :=
        IntermediateField.subset_adjoin ℚ _ (Or.inr ⟨1, exp_family_one⟩)
      have hden : (2 : ℂ) ∈ generatedField family :=
        IntermediateField.algebraMap_mem _ (2 : ℚ)
      have := (generatedField family).div_mem hnum hden
      simpa using this

/-- The reduced pair, regarded inside the Schanuel field of the mixed family. -/
def liftedCore : Fin 2 → generatedField family := fun i ↦
  ⟨core i, by
    rw [generatedField_eq_adjoin_core]
    exact IntermediateField.subset_adjoin ℚ _ (Set.mem_range_self i)⟩

@[simp]
theorem coe_liftedCore (i : Fin 2) : (liftedCore i : ℂ) = core i := rfl

theorem image_val_range_liftedCore :
    Subtype.val '' Set.range liftedCore = Set.range core := by
  ext x
  simp only [Set.mem_image, Set.mem_range]
  constructor
  · rintro ⟨y, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨liftedCore i, ⟨i, rfl⟩, rfl⟩

theorem adjoin_range_liftedCore_eq_top :
    IntermediateField.adjoin ℚ (Set.range liftedCore) = ⊤ := by
  apply IntermediateField.map_injective (inclusion family)
  rw [IntermediateField.adjoin_map, ← AlgHom.fieldRange_eq_map]
  rw [show inclusion family '' Set.range liftedCore =
      Subtype.val '' Set.range liftedCore by rfl]
  rw [image_val_range_liftedCore, fieldRange_inclusion, generatedField_eq_adjoin_core]

open scoped IntermediateField.algebraAdjoinAdjoin in
theorem isAlgebraic_adjoin_range_liftedCore :
    Algebra.IsAlgebraic
      (Algebra.adjoin ℚ (Set.range liftedCore)) (generatedField family) := by
  let f :
      IntermediateField.adjoin ℚ (Set.range liftedCore) →ₐ[
        Algebra.adjoin ℚ (Set.range liftedCore)] generatedField family :=
    IsScalarTower.toAlgHom _ _ _
  have hf_surj : Function.Surjective f := by
    intro x
    refine ⟨⟨x, ?_⟩, rfl⟩
    rw [adjoin_range_liftedCore_eq_top]
    exact IntermediateField.mem_top
  let e := AlgEquiv.ofBijective f ⟨f.injective, hf_surj⟩
  exact e.isAlgebraic

/-- Schanuel's bound for the elementary mixed family is exactly the algebraic independence of
`log 2` and `e`.  This is the sharp obstruction to extending the algebraic-input theorem by a
pure base-change or specialization argument. -/
theorem bound_family_iff_algebraicIndependent_logTwo_exp_one :
    Bound family ↔ AlgebraicIndependent ℚ core := by
  constructor
  · intro hbound
    letI : Algebra.IsAlgebraic
        (Algebra.adjoin ℚ (Set.range liftedCore)) (generatedField family) :=
      isAlgebraic_adjoin_range_liftedCore
    have htb : IsTranscendenceBasis ℚ liftedCore :=
      Algebra.IsAlgebraic.isTranscendenceBasis_of_le_trdeg ℚ liftedCore
        (trdeg_lt_aleph0 family) hbound
    have hcomplex := htb.1.map' (generatedField family).val.injective
    simpa [Function.comp_def] using hcomplex
  · intro hcore
    have hlifted : AlgebraicIndependent ℚ liftedCore := by
      apply AlgebraicIndependent.of_comp (generatedField family).val
      simpa [Function.comp_def] using hcore
    exact hlifted.cardinalMk_le_trdeg

/-- The full conjecture would in particular settle the concrete algebraic-independence statement
for `log 2` and `e`. -/
theorem conjecture_implies_algebraicIndependent_logTwo_exp_one
    (hS : Conjecture) : AlgebraicIndependent ℚ core := by
  apply bound_family_iff_algebraicIndependent_logTwo_exp_one.mp
  exact hS 2 family family_linearIndependent

end

end Schanuel.MixedObstruction
