import Schanuel.RationalScaling
import Schanuel.RelativeDescent
import Mathlib.Algebra.Module.LocalizedModule.Int
import Mathlib.LinearAlgebra.Matrix.ToLinearEquiv

/-!
# Rational changes of basis for exponential families

An invertible rational matrix preserves both rational linear independence and the
transcendence degree of the field generated by a finite family together with its
coordinatewise exponentials.  Denominators are cleared in the matrix and its inverse.
The resulting integer linear combinations give inclusions of generated fields, while
positive rational scalar invariance supplies the reverse comparison.
-/

namespace Schanuel

open Function Set
open scoped Matrix

noncomputable section

/-- The family obtained by applying a rational matrix to a complex family. -/
def rationalMatrixFamily {n : ℕ} (B : Matrix (Fin n) (Fin n) ℚ)
    (z : Fin n → ℂ) : Fin n → ℂ :=
  fun i ↦ ∑ j, B i j • z j

/-- The family obtained by applying an integer matrix to a complex family. -/
def integerMatrixFamily {n : ℕ} (A : Matrix (Fin n) (Fin n) ℤ)
    (z : Fin n → ℂ) : Fin n → ℂ :=
  fun i ↦ ∑ j, (A i j : ℚ) • z j

@[simp]
theorem rationalMatrixFamily_one {n : ℕ} (z : Fin n → ℂ) :
    rationalMatrixFamily (1 : Matrix (Fin n) (Fin n) ℚ) z = z := by
  classical
  funext i
  rw [rationalMatrixFamily, Finset.sum_eq_single i]
  · simp
  · intro j hj hji
    simp [Ne.symm hji]
  · simp

theorem rationalMatrixFamily_mul {n : ℕ}
    (A B : Matrix (Fin n) (Fin n) ℚ) (z : Fin n → ℂ) :
    rationalMatrixFamily A (rationalMatrixFamily B z) =
      rationalMatrixFamily (A * B) z := by
  funext i
  simp only [rationalMatrixFamily, Matrix.mul_apply, Finset.smul_sum,
    smul_smul, Finset.sum_smul]
  rw [Finset.sum_comm]

/-- Applying an invertible rational matrix preserves rational linear independence. -/
theorem linearIndependent_rationalMatrixFamily {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) (hB : B.det ≠ 0) (z : Fin n → ℂ)
    (hz : LinearIndependent ℚ z) :
    LinearIndependent ℚ (rationalMatrixFamily B z) := by
  exact hz.sum_smul_of_nondegenerate
    ((Matrix.nondegenerate_iff_det_ne_zero).2 hB)

theorem linearIndependent_rationalMatrixFamily_iff {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) (hB : B.det ≠ 0) (z : Fin n → ℂ) :
    LinearIndependent ℚ (rationalMatrixFamily B z) ↔ LinearIndependent ℚ z := by
  constructor
  · intro hw
    have hunit : IsUnit B.det := isUnit_iff_ne_zero.mpr hB
    have hinvunit : IsUnit (B⁻¹).det :=
      B.isUnit_nonsing_inv_det hunit
    have hinvdet : (B⁻¹).det ≠ 0 := hinvunit.ne_zero
    have hi := linearIndependent_rationalMatrixFamily B⁻¹ hinvdet
      (rationalMatrixFamily B z) hw
    rw [rationalMatrixFamily_mul, Matrix.nonsing_inv_mul B hunit,
      rationalMatrixFamily_one] at hi
    exact hi
  · exact linearIndependent_rationalMatrixFamily B hB z

/-- A finite rational matrix has a positive integer scalar multiple with integer entries. -/
theorem exists_pos_integer_matrix_scale {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) :
    ∃ d : ℤ, 0 < d ∧ ∃ A : Matrix (Fin n) (Fin n) ℤ,
      ∀ i j, (A i j : ℚ) = (d : ℚ) * B i j := by
  let f : (Fin n × Fin n) → ℚ := fun ij ↦ B ij.1 ij.2
  obtain ⟨b, hb⟩ := IsLocalization.exist_integer_multiples_of_finite
    (nonZeroDivisors ℤ) f
  choose A hA using fun i j ↦ hb (i, j)
  let d : ℤ := (b : ℤ) ^ 2
  let C : Matrix (Fin n) (Fin n) ℤ := fun i j ↦ (b : ℤ) * A i j
  refine ⟨d, sq_pos_of_ne_zero (nonZeroDivisors.coe_ne_zero b), C, ?_⟩
  intro i j
  have hij := hA i j
  change algebraMap ℤ ℚ (A i j) = ((b : ℤ) : ℚ) • B i j at hij
  change (((b : ℤ) * A i j : ℤ) : ℚ) = (((b : ℤ) ^ 2 : ℤ) : ℚ) * B i j
  calc
    (((b : ℤ) * A i j : ℤ) : ℚ) = ((b : ℤ) : ℚ) * (A i j : ℚ) := by
      exact_mod_cast rfl
    _ = ((b : ℤ) : ℚ) * (((b : ℤ) : ℚ) * B i j) := by
      congr 1
    _ = (((b : ℤ) ^ 2 : ℤ) : ℚ) * B i j := by
      push_cast
      ring

/-- Clearing the entries of a rational matrix amounts to one positive rational scaling
of its transformed family. -/
theorem integerMatrixFamily_eq_ratScaleFamily {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) (d : ℤ)
    (A : Matrix (Fin n) (Fin n) ℤ)
    (hA : ∀ i j, (A i j : ℚ) = (d : ℚ) * B i j)
    (z : Fin n → ℂ) :
    integerMatrixFamily A z =
      ratScaleFamily (d : ℚ) (rationalMatrixFamily B z) := by
  funext i
  simp only [integerMatrixFamily, ratScaleFamily, rationalMatrixFamily]
  simp_rw [hA, mul_smul]
  change (∑ j, (d : ℚ) • (B i j • z j)) =
    (d : ℚ) • ∑ j, B i j • z j
  exact Finset.smul_sum.symm

/-- Rational linear combinations of the coordinates stay in the original coordinate field. -/
theorem coordinateField_rationalMatrixFamily_le {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) (z : Fin n → ℂ) :
    coordinateField (rationalMatrixFamily B z) ≤ coordinateField z := by
  rw [coordinateField, IntermediateField.adjoin_le_iff]
  rintro x ⟨i, rfl⟩
  change (∑ j, B i j • z j) ∈ coordinateField z
  apply (coordinateField z).sum_mem
  intro j hj
  rw [Rat.smul_def]
  exact (coordinateField z).mul_mem
    (IntermediateField.algebraMap_mem _ (B i j))
    (IntermediateField.subset_adjoin ℚ _ ⟨j, rfl⟩)

/-- An invertible rational change of basis leaves the coordinate field unchanged. -/
theorem coordinateField_rationalMatrixFamily_eq {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) (hB : B.det ≠ 0) (z : Fin n → ℂ) :
    coordinateField (rationalMatrixFamily B z) = coordinateField z := by
  have hunit : IsUnit B.det := isUnit_iff_ne_zero.mpr hB
  apply le_antisymm (coordinateField_rationalMatrixFamily_le B z)
  have hle := coordinateField_rationalMatrixFamily_le B⁻¹
    (rationalMatrixFamily B z)
  rw [rationalMatrixFamily_mul, Matrix.nonsing_inv_mul B hunit,
    rationalMatrixFamily_one] at hle
  exact hle

/-- Integer linear combinations introduce no new coordinate or exponential generators. -/
theorem generatedField_integerMatrixFamily_le {n : ℕ}
    (A : Matrix (Fin n) (Fin n) ℤ) (z : Fin n → ℂ) :
    generatedField (integerMatrixFamily A z) ≤ generatedField z := by
  rw [generatedField, IntermediateField.adjoin_le_iff]
  rintro x (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · change (∑ j, (A i j : ℚ) • z j) ∈ generatedField z
    apply (generatedField z).sum_mem
    intro j hj
    rw [Rat.smul_def]
    exact (generatedField z).mul_mem
      (IntermediateField.algebraMap_mem _ (A i j : ℚ))
      (IntermediateField.subset_adjoin ℚ _ (Or.inl ⟨j, rfl⟩))
  · change Complex.exp (∑ j, (A i j : ℚ) • z j) ∈ generatedField z
    rw [Complex.exp_sum]
    apply (generatedField z).prod_mem
    intro j hj
    rw [Rat.smul_def, Rat.cast_intCast, Complex.exp_int_mul]
    exact (generatedField z).pow_mem
      (IntermediateField.subset_adjoin ℚ _ (Or.inr ⟨j, rfl⟩)) (A i j)

/-- Every transformed exponential is integral over the original full generated field.
The monic equation is obtained by clearing all matrix denominators at once. -/
theorem exp_rationalMatrixFamily_isIntegral {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) (z : Fin n → ℂ) (i : Fin n) :
    IsIntegral (generatedField z) (Complex.exp (rationalMatrixFamily B z i)) := by
  obtain ⟨d, hd, A, hA⟩ := exists_pos_integer_matrix_scale B
  have hscale := congrFun (integerMatrixFamily_eq_ratScaleFamily B d A hA z) i
  have hmem : Complex.exp (integerMatrixFamily A z i) ∈ generatedField z :=
    generatedField_integerMatrixFamily_le A z
      (IntermediateField.subset_adjoin ℚ _ (Or.inr ⟨i, rfl⟩))
  have hdNat : 0 < d.toNat := by omega
  have hdcast : ((d.toNat : ℕ) : ℂ) = (d : ℂ) := by
    exact_mod_cast Int.toNat_of_nonneg hd.le
  have hpow : Complex.exp (rationalMatrixFamily B z i) ^ d.toNat ∈ generatedField z := by
    rw [← Complex.exp_nat_mul, hdcast]
    convert hmem using 1
    exact congrArg Complex.exp hscale.symm
  exact IsIntegral.of_pow hdNat
    (isIntegral_of_mem_intermediateField (generatedField z) hpow)

/-- Transcendence degree is monotone under inclusion of the concrete generated fields. -/
theorem trdeg_generatedField_le_of_le {m n : ℕ} {w : Fin m → ℂ} {z : Fin n → ℂ}
    (h : generatedField w ≤ generatedField z) :
    Algebra.trdeg ℚ (generatedField w) ≤ Algebra.trdeg ℚ (generatedField z) := by
  let f : generatedField w →ₐ[ℚ] generatedField z :=
    (IntermediateField.inclusion h).toRingHom.toRatAlgHom
  exact trdeg_le_of_injective f
    (IntermediateField.inclusion_injective h)

/-- An invertible rational change of basis preserves the transcendence degree of the full
coordinate-exponential generating field. -/
theorem trdeg_rationalMatrixFamily_eq {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) (hB : B.det ≠ 0) (z : Fin n → ℂ) :
    Algebra.trdeg ℚ (generatedField (rationalMatrixFamily B z)) =
      Algebra.trdeg ℚ (generatedField z) := by
  have hunit : IsUnit B.det := isUnit_iff_ne_zero.mpr hB
  obtain ⟨d, hd, A, hA⟩ := exists_pos_integer_matrix_scale B
  obtain ⟨e, he, C, hC⟩ := exists_pos_integer_matrix_scale B⁻¹
  have hdQ : (0 : ℚ) < d := by exact_mod_cast hd
  have heQ : (0 : ℚ) < e := by exact_mod_cast he
  apply le_antisymm
  · rw [← trdeg_ratScaleFamily_eq (d : ℚ) hdQ (rationalMatrixFamily B z),
      ← integerMatrixFamily_eq_ratScaleFamily B d A hA z]
    exact trdeg_generatedField_le_of_le
      (generatedField_integerMatrixFamily_le A z)
  · rw [← trdeg_ratScaleFamily_eq (e : ℚ) heQ z]
    have hle := generatedField_integerMatrixFamily_le C (rationalMatrixFamily B z)
    have hcancel :
        integerMatrixFamily C (rationalMatrixFamily B z) = ratScaleFamily (e : ℚ) z := by
      rw [integerMatrixFamily_eq_ratScaleFamily B⁻¹ e C hC,
        rationalMatrixFamily_mul, Matrix.nonsing_inv_mul B hunit,
        rationalMatrixFamily_one]
    rw [hcancel] at hle
    exact trdeg_generatedField_le_of_le hle

/-- The Schanuel bound is invariant under an invertible rational change of basis. -/
theorem bound_rationalMatrixFamily_iff {n : ℕ}
    (B : Matrix (Fin n) (Fin n) ℚ) (hB : B.det ≠ 0) (z : Fin n → ℂ) :
    Bound (rationalMatrixFamily B z) ↔ Bound z := by
  rw [Bound, Bound, trdeg_rationalMatrixFamily_eq B hB z]

end

end Schanuel
