import Schanuel

/-!
# Positive rational scaling of exponential generating fields

Multiplying every exponent by a nonzero positive rational does not change the transcendence degree
of the field generated by the exponents and their exponentials.  The two generated fields need not
be nested.  We compare each of them with an algebraic extension obtained by adjoining the other
family's generators.
-/

namespace Schanuel

open Function Set

noncomputable section

/-- Pointwise multiplication of a finite complex family by a rational number. -/
def ratScaleFamily {n : ℕ} (a : ℚ) (z : Fin n → ℂ) : Fin n → ℂ :=
  fun i ↦ (a : ℂ) * z i

/-- The power relation between the exponentials before and after positive rational scaling. -/
theorem exp_pow_num_eq_exp_rat_mul_pow (a : ℚ) (ha : 0 < a) (z : ℂ) :
    Complex.exp z ^ a.num.toNat = Complex.exp ((a : ℂ) * z) ^ a.den := by
  rw [← Complex.exp_nat_mul, ← Complex.exp_nat_mul]
  congr 1
  have hnum_nonneg : 0 ≤ a.num := (Rat.num_pos.mpr ha).le
  have hmul : (a.den : ℚ) * a = a.num := by
    have hden : (a.den : ℚ) ≠ 0 := by exact_mod_cast a.den_nz
    have hnum : (a.num : ℚ) = a * a.den :=
      (div_eq_iff hden).mp a.num_div_den
    calc
      (a.den : ℚ) * a = a * a.den := mul_comm _ _
      _ = a.num := hnum.symm
  have hcast : ((a.num.toNat : ℕ) : ℂ) = (a.num : ℂ) := by
    exact_mod_cast Int.toNat_of_nonneg hnum_nonneg
  have hmulC : (a.den : ℂ) * (a : ℂ) = (a.num : ℂ) := by
    exact_mod_cast hmul
  rw [hcast, ← hmulC]
  ring

theorem rat_num_toNat_pos {a : ℚ} (ha : 0 < a) : 0 < a.num.toNat := by
  have hnum : 0 < a.num := Rat.num_pos.mpr ha
  have hnum_nonneg : 0 ≤ a.num := hnum.le
  have hnatInt : (0 : ℤ) < (a.num.toNat : ℕ) := by
    rw [Int.toNat_of_nonneg hnum_nonneg]
    exact hnum
  exact_mod_cast hnatInt

theorem isIntegral_of_mem_intermediateField (F : IntermediateField ℚ ℂ)
    {x : ℂ} (hx : x ∈ F) : IsIntegral F x := by
  let y : F := ⟨x, hx⟩
  have hy : IsIntegral F ((algebraMap F ℂ) y) := isIntegral_algebraMap
  exact hy

theorem mem_generatedField_ratScale_coordinate {n : ℕ} (a : ℚ) (ha : a ≠ 0)
    (z : Fin n → ℂ) (i : Fin n) :
    z i ∈ generatedField (ratScaleFamily a z) := by
  have hscaled : (a : ℂ) * z i ∈ generatedField (ratScaleFamily a z) :=
    IntermediateField.subset_adjoin ℚ _ (Or.inl ⟨i, rfl⟩)
  have ha_mem : (a : ℂ) ∈ generatedField (ratScaleFamily a z) :=
    IntermediateField.algebraMap_mem _ a
  have hdiv := (generatedField (ratScaleFamily a z)).div_mem hscaled ha_mem
  have haC : (a : ℂ) ≠ 0 := by exact_mod_cast ha
  convert hdiv using 1
  field_simp

theorem mem_generatedField_ratScale_scaledCoordinate {n : ℕ} (a : ℚ)
    (z : Fin n → ℂ) (i : Fin n) :
    (a : ℂ) * z i ∈ generatedField z := by
  exact (generatedField z).mul_mem
    (IntermediateField.algebraMap_mem _ a)
    (IntermediateField.subset_adjoin ℚ _ (Or.inl ⟨i, rfl⟩))

theorem exp_isIntegral_over_ratScale {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) (i : Fin n) :
    IsIntegral (generatedField (ratScaleFamily a z)) (Complex.exp (z i)) := by
  let F := generatedField (ratScaleFamily a z)
  have hscaledexp : Complex.exp ((a : ℂ) * z i) ∈ F :=
    IntermediateField.subset_adjoin ℚ _ (Or.inr ⟨i, rfl⟩)
  have hpowscaled : Complex.exp ((a : ℂ) * z i) ^ a.den ∈ F :=
    F.pow_mem hscaledexp a.den
  have hpowmem : Complex.exp (z i) ^ a.num.toNat ∈ F := by
    rw [exp_pow_num_eq_exp_rat_mul_pow a ha]
    exact hpowscaled
  exact IsIntegral.of_pow (rat_num_toNat_pos ha)
    (isIntegral_of_mem_intermediateField F hpowmem)

theorem scaledExp_isIntegral_over_original {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) (i : Fin n) :
    IsIntegral (generatedField z) (Complex.exp ((a : ℂ) * z i)) := by
  let F := generatedField z
  have hexp : Complex.exp (z i) ∈ F :=
    IntermediateField.subset_adjoin ℚ _ (Or.inr ⟨i, rfl⟩)
  have hpow : Complex.exp (z i) ^ a.num.toNat ∈ F :=
    F.pow_mem hexp a.num.toNat
  have hscaledpow : Complex.exp ((a : ℂ) * z i) ^ a.den ∈ F := by
    rw [← exp_pow_num_eq_exp_rat_mul_pow a ha]
    exact hpow
  exact IsIntegral.of_pow a.den_pos
    (isIntegral_of_mem_intermediateField F hscaledpow)

theorem generators_isIntegral_over_ratScale {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) :
    ∀ x ∈ generators z,
      IsIntegral (generatedField (ratScaleFamily a z)) x := by
  rintro x (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · exact isIntegral_of_mem_intermediateField _
      (mem_generatedField_ratScale_coordinate a ha.ne' z i)
  · exact exp_isIntegral_over_ratScale a ha z i

theorem scaledGenerators_isIntegral_over_original {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) :
    ∀ x ∈ generators (ratScaleFamily a z), IsIntegral (generatedField z) x := by
  rintro x (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · exact isIntegral_of_mem_intermediateField _
      (mem_generatedField_ratScale_scaledCoordinate a z i)
  · exact scaledExp_isIntegral_over_original a ha z i

/-- Adjoin the original generators over the field generated by the scaled family. -/
def scaledAdjoinOriginal {n : ℕ} (a : ℚ) (z : Fin n → ℂ) :
    IntermediateField (generatedField (ratScaleFamily a z)) ℂ :=
  IntermediateField.adjoin (generatedField (ratScaleFamily a z)) (generators z)

/-- Adjoin the scaled generators over the field generated by the original family. -/
def originalAdjoinScaled {n : ℕ} (a : ℚ) (z : Fin n → ℂ) :
    IntermediateField (generatedField z) ℂ :=
  IntermediateField.adjoin (generatedField z) (generators (ratScaleFamily a z))

theorem originalToScaledAdjoin_le {n : ℕ} (a : ℚ) (z : Fin n → ℂ) :
    generatedField z ≤ (scaledAdjoinOriginal a z).restrictScalars ℚ := by
  change IntermediateField.adjoin ℚ (generators z) ≤
    (IntermediateField.adjoin (generatedField (ratScaleFamily a z))
      (generators z)).restrictScalars ℚ
  rw [show (IntermediateField.adjoin (generatedField (ratScaleFamily a z))
      (generators z)).restrictScalars ℚ =
      generatedField (ratScaleFamily a z) ⊔ IntermediateField.adjoin ℚ (generators z) from
    IntermediateField.restrictScalars_adjoin_eq_sup ℚ
      (generatedField (ratScaleFamily a z)) (generators z)]
  exact le_sup_right

theorem scaledToOriginalAdjoin_le {n : ℕ} (a : ℚ) (z : Fin n → ℂ) :
    generatedField (ratScaleFamily a z) ≤
      (originalAdjoinScaled a z).restrictScalars ℚ := by
  change IntermediateField.adjoin ℚ (generators (ratScaleFamily a z)) ≤
    (IntermediateField.adjoin (generatedField z)
      (generators (ratScaleFamily a z))).restrictScalars ℚ
  rw [show (IntermediateField.adjoin (generatedField z)
      (generators (ratScaleFamily a z))).restrictScalars ℚ =
      generatedField z ⊔ IntermediateField.adjoin ℚ (generators (ratScaleFamily a z)) from
    IntermediateField.restrictScalars_adjoin_eq_sup ℚ
      (generatedField z) (generators (ratScaleFamily a z))]
  exact le_sup_right

def originalToScaledAdjoin {n : ℕ} (a : ℚ) (z : Fin n → ℂ) :
    generatedField z →ₐ[ℚ] scaledAdjoinOriginal a z :=
  IntermediateField.inclusion (originalToScaledAdjoin_le a z)

def scaledToOriginalAdjoin {n : ℕ} (a : ℚ) (z : Fin n → ℂ) :
    generatedField (ratScaleFamily a z) →ₐ[ℚ] originalAdjoinScaled a z :=
  IntermediateField.inclusion (scaledToOriginalAdjoin_le a z)

theorem scaledAdjoinOriginal_isAlgebraic {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) :
    Algebra.IsAlgebraic (generatedField (ratScaleFamily a z))
      (scaledAdjoinOriginal a z) := by
  exact IntermediateField.isAlgebraic_adjoin
    (generators_isIntegral_over_ratScale a ha z)

theorem originalAdjoinScaled_isAlgebraic {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) :
    Algebra.IsAlgebraic (generatedField z) (originalAdjoinScaled a z) := by
  exact IntermediateField.isAlgebraic_adjoin
    (scaledGenerators_isIntegral_over_original a ha z)

theorem trdeg_scaledAdjoinOriginal_eq {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) :
    Algebra.trdeg ℚ (scaledAdjoinOriginal a z) =
      Algebra.trdeg ℚ (generatedField (ratScaleFamily a z)) := by
  letI : Algebra.IsAlgebraic (generatedField (ratScaleFamily a z))
      (scaledAdjoinOriginal a z) := scaledAdjoinOriginal_isAlgebraic a ha z
  have hzero : Algebra.trdeg (generatedField (ratScaleFamily a z))
      (scaledAdjoinOriginal a z) = 0 := trdeg_eq_zero
  have h := trdeg_add_eq ℚ (generatedField (ratScaleFamily a z))
    (A := scaledAdjoinOriginal a z)
  rw [hzero, add_zero] at h
  exact h.symm

theorem trdeg_originalAdjoinScaled_eq {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) :
    Algebra.trdeg ℚ (originalAdjoinScaled a z) =
      Algebra.trdeg ℚ (generatedField z) := by
  letI : Algebra.IsAlgebraic (generatedField z) (originalAdjoinScaled a z) :=
    originalAdjoinScaled_isAlgebraic a ha z
  have hzero : Algebra.trdeg (generatedField z) (originalAdjoinScaled a z) = 0 :=
    trdeg_eq_zero
  have h := trdeg_add_eq ℚ (generatedField z) (A := originalAdjoinScaled a z)
  rw [hzero, add_zero] at h
  exact h.symm

/-- Positive rational rescaling preserves the transcendence degree of the full exponential
generating field. -/
theorem trdeg_ratScaleFamily_eq {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) :
    Algebra.trdeg ℚ (generatedField (ratScaleFamily a z)) =
      Algebra.trdeg ℚ (generatedField z) := by
  apply le_antisymm
  · calc
      Algebra.trdeg ℚ (generatedField (ratScaleFamily a z)) ≤
          Algebra.trdeg ℚ (originalAdjoinScaled a z) :=
        trdeg_le_of_injective (scaledToOriginalAdjoin a z)
          (scaledToOriginalAdjoin a z).injective
      _ = Algebra.trdeg ℚ (generatedField z) :=
        trdeg_originalAdjoinScaled_eq a ha z
  · calc
      Algebra.trdeg ℚ (generatedField z) ≤
          Algebra.trdeg ℚ (scaledAdjoinOriginal a z) :=
        trdeg_le_of_injective (originalToScaledAdjoin a z)
          (originalToScaledAdjoin a z).injective
      _ = Algebra.trdeg ℚ (generatedField (ratScaleFamily a z)) :=
        trdeg_scaledAdjoinOriginal_eq a ha z

theorem bound_ratScaleFamily_iff {n : ℕ} (a : ℚ) (ha : 0 < a)
    (z : Fin n → ℂ) : Bound (ratScaleFamily a z) ↔ Bound z := by
  rw [Bound, Bound, trdeg_ratScaleFamily_eq a ha z]

end


end Schanuel
