import Schanuel
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic

/-!
# Relative transcendence degree and a specialization obstruction

Separating the field generated by the coordinates from the exponentials gives an exact
tower decomposition of the transcendence degree.  This is the algebraic part of the
often-proposed specialization route to Schanuel's conjecture.

The last theorem records the obstruction to its analytic part.  A specialization may
transport algebraic relations, but even a set map fixing `1` cannot both send the basic
period `2 * pi * I` to `1` and commute with the complex exponential.  In particular,
exponential compatibility cannot be silently added to a field-theoretic specialization.
-/

namespace Schanuel

open Set

noncomputable section

/-- The subfield generated by the coordinates, before adjoining their exponentials. -/
def coordinateField {n : ℕ} (z : Fin n → ℂ) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ (Set.range z)

theorem coordinateField_le_generatedField {n : ℕ} (z : Fin n → ℂ) :
    coordinateField z ≤ generatedField z := by
  apply IntermediateField.adjoin.mono
  exact fun _ hx ↦ Or.inl hx

noncomputable instance coordinateFieldAlgebraGeneratedField {n : ℕ} (z : Fin n → ℂ) :
    Algebra (coordinateField z) (generatedField z) :=
  (IntermediateField.inclusion (coordinateField_le_generatedField z)).toRingHom.toAlgebra

instance coordinateFieldIsScalarTower {n : ℕ} (z : Fin n → ℂ) :
    IsScalarTower ℚ (coordinateField z) (generatedField z) :=
  IsScalarTower.of_algebraMap_eq fun _ ↦ rfl

/-- The total transcendence degree is exactly the contribution from the coordinates plus the
remaining relative contribution after the coordinates have been adjoined. -/
theorem trdeg_coordinate_add_relative {n : ℕ} (z : Fin n → ℂ) :
    Algebra.trdeg ℚ (coordinateField z) +
        Algebra.trdeg (coordinateField z) (generatedField z) =
      Algebra.trdeg ℚ (generatedField z) := by
  exact trdeg_add_eq ℚ (coordinateField z)

/-- After the coordinates have become scalars, the exponentials alone field-generate the total
extension. -/
theorem relativeAdjoin_exponential_eq_top {n : ℕ} (z : Fin n → ℂ) :
    IntermediateField.adjoin (coordinateField z) (Set.range (exponential z)) = ⊤ := by
  let E := IntermediateField.adjoin (coordinateField z) (Set.range (exponential z))
  apply top_unique
  intro x _
  change x ∈ E
  have hx : (x : ℂ) ∈ IntermediateField.adjoin ℚ (generators z) := x.property
  let p : ∀ y ∈ IntermediateField.adjoin ℚ (generators z), Prop :=
    fun y hy ↦ (⟨y, hy⟩ : generatedField z) ∈ E
  exact IntermediateField.adjoin_induction ℚ (p := p)
    (fun y hy ↦ by
      rcases hy with ⟨i, rfl⟩ | ⟨i, rfl⟩
      · have hi : z i ∈ coordinateField z :=
          IntermediateField.subset_adjoin ℚ _ ⟨i, rfl⟩
        exact E.algebraMap_mem ⟨z i, hi⟩
      · exact IntermediateField.subset_adjoin (coordinateField z) _ ⟨i, rfl⟩)
    (fun q ↦ by
      have hq : (q : ℂ) ∈ coordinateField z :=
        IntermediateField.algebraMap_mem _ q
      exact E.algebraMap_mem ⟨(q : ℂ), hq⟩)
    (fun _ _ _ _ ha hb ↦ E.add_mem ha hb)
    (fun _ _ ha ↦ E.inv_mem ha)
    (fun _ _ _ _ ha hb ↦ E.mul_mem ha hb)
    hx

open scoped IntermediateField.algebraAdjoinAdjoin in
/-- The total generated field is algebraic over the coordinate field with the exponential family
adjoined as an algebra. -/
theorem isAlgebraic_adjoin_range_exponential_relative {n : ℕ} (z : Fin n → ℂ) :
    Algebra.IsAlgebraic
      (Algebra.adjoin (coordinateField z) (Set.range (exponential z)))
      (generatedField z) := by
  let f :
      IntermediateField.adjoin (coordinateField z) (Set.range (exponential z)) →ₐ[
        Algebra.adjoin (coordinateField z) (Set.range (exponential z))]
        generatedField z :=
    IsScalarTower.toAlgHom _ _ _
  have hf_surj : Function.Surjective f := by
    intro x
    refine ⟨⟨x, ?_⟩, rfl⟩
    rw [relativeAdjoin_exponential_eq_top]
    exact IntermediateField.mem_top
  let e := AlgEquiv.ofBijective f ⟨f.injective, hf_surj⟩
  exact e.isAlgebraic

/-- The exponentials can contribute at most `n` new transcendence degrees over the coordinate
field.  Schanuel's conjecture asks for the complementary lower bound determined by the coordinate
contribution. -/
theorem relative_trdeg_le_cardinalMk_fin {n : ℕ} (z : Fin n → ℂ) :
    Algebra.trdeg (coordinateField z) (generatedField z) ≤ Cardinal.mk (Fin n) := by
  letI : Algebra.IsAlgebraic
      (Algebra.adjoin (coordinateField z) (Set.range (exponential z)))
      (generatedField z) :=
    isAlgebraic_adjoin_range_exponential_relative z
  exact (Algebra.IsAlgebraic.trdeg_le_cardinalMk
    (coordinateField z) (Set.range (exponential z))).trans Cardinal.mk_range_le

theorem relative_trdeg_le_natCast {n : ℕ} (z : Fin n → ℂ) :
    Algebra.trdeg (coordinateField z) (generatedField z) ≤ ((n : ℕ) : Cardinal) := by
  simpa using relative_trdeg_le_cardinalMk_fin z

/-- Schanuel's bound, rewritten as the exact relative-transcendence-degree target. -/
theorem bound_iff_coordinate_add_relative {n : ℕ} (z : Fin n → ℂ) :
    Bound z ↔ Cardinal.mk (Fin n) ≤
      Algebra.trdeg ℚ (coordinateField z) +
        Algebra.trdeg (coordinateField z) (generatedField z) := by
  rw [trdeg_coordinate_add_relative]
  rfl

/-- An injective algebra homomorphism cannot turn a transcendental element into an algebraic
one.  Thus a geometric specialization of transcendence parameters is not a homomorphism on the
whole function field; it must first be restricted to a suitable subalgebra (or expressed as a
place). -/
theorem transcendental_algHom_of_injective
    {R A B : Type*} [CommRing R] [CommRing A] [CommRing B]
    [Algebra R A] [Algebra R B] (f : A →ₐ[R] B) (hf : Function.Injective f)
    {x : A} (hx : Transcendental R x) : Transcendental R (f x) := by
  intro hfx
  exact hx ((isAlgebraic_algHom_iff f hf).mp hfx)

theorem algHom_image_ne_algebraic_of_transcendental
    {R A B : Type*} [CommRing R] [CommRing A] [CommRing B]
    [Algebra R A] [Algebra R B] (f : A →ₐ[R] B) (hf : Function.Injective f)
    {x : A} (hx : Transcendental R x) {y : B} (hy : IsAlgebraic R y) : f x ≠ y := by
  intro hxy
  exact (transcendental_algHom_of_injective f hf hx) (hxy ▸ hy)

theorem complex_exp_one_ne_one : Complex.exp (1 : ℂ) ≠ 1 := by
  intro h
  have hre := congrArg Complex.re h
  change (Complex.exp ((1 : ℝ) : ℂ)).re = (1 : ℝ) at hre
  rw [Complex.exp_ofReal_re] at hre
  have hlt : (1 : ℝ) < Real.exp 1 := Real.one_lt_exp_iff.mpr zero_lt_one
  rw [hre] at hlt
  exact lt_irrefl 1 hlt

/-- There is no exponential-compatible specialization sending the basic period to `1`, even
before requiring the specializing map to preserve any field operations. -/
theorem no_exp_compatible_period_specialization
    (phi : ℂ → ℂ) (h_one : phi 1 = 1)
    (h_period : phi (2 * Real.pi * Complex.I) = 1)
    (h_exp : ∀ x : ℂ, phi (Complex.exp x) = Complex.exp (phi x)) : False := by
  have h := h_exp (2 * Real.pi * Complex.I)
  rw [Complex.exp_two_pi_mul_I, h_one, h_period] at h
  exact complex_exp_one_ne_one h.symm

end

end Schanuel
