import Schanuel

/-!
# A finite-selection form of Schanuel's conjecture

The field in `Schanuel.Bound` is generated by the displayed family
`z₁, ..., zₙ, exp z₁, ..., exp zₙ`.  Consequently, its transcendence-degree lower bound is
equivalent to the existence of `n` algebraically independent members of that family.
-/

namespace Schanuel

open Function Set

noncomputable section

theorem exists_transcendenceBasis_subset_expPair {n : ℕ} (z : Fin n → ℂ) :
    ∃ t : Set (generatedField z), t ⊆ range (liftedExpPair z) ∧
      IsTranscendenceBasis ℚ ((↑) : t → generatedField z) := by
  letI : Algebra.IsAlgebraic (Algebra.adjoin ℚ (range (liftedExpPair z)))
      (generatedField z) := isAlgebraic_adjoin_range_liftedExpPair z
  exact exists_isTranscendenceBasis_subset (R := ℚ) (A := generatedField z)
    (range (liftedExpPair z))

/-- Schanuel's numerical bound is equivalent to finding `n` algebraically independent
elements among the `2n` displayed coordinates and exponentials. -/
theorem bound_iff_exists_algebraicIndependent_subfamily {n : ℕ} (z : Fin n → ℂ) :
    Bound z ↔ ∃ f : Fin n → Fin n ⊕ Fin n,
      AlgebraicIndependent ℚ (expPair z ∘ f) := by
  constructor
  · intro hz
    obtain ⟨t, ht, htb⟩ := exists_transcendenceBasis_subset_expPair z
    have hcard : Cardinal.mk (Fin n) ≤ Cardinal.mk t := by
      rw [htb.cardinalMk_eq_trdeg]
      exact hz
    obtain ⟨e⟩ : Nonempty (Fin n ↪ t) := hcard
    let incl : t → range (liftedExpPair z) := Set.inclusion ht
    let f : Fin n → Fin n ⊕ Fin n :=
      rangeSplitting (liftedExpPair z) ∘ incl ∘ e
    refine ⟨f, ?_⟩
    have heField : AlgebraicIndependent ℚ
        (((↑) : t → generatedField z) ∘ e) := htb.1.comp e e.injective
    have heComplex := heField.map' (generatedField z).val.injective
    convert heComplex using 1
    funext i
    change ((liftedExpPair z
      (rangeSplitting (liftedExpPair z) (incl (e i))) : generatedField z) : ℂ) =
        ((e i : generatedField z) : ℂ)
    simpa [incl] using congrArg ((↑) : generatedField z → ℂ)
      (Set.apply_rangeSplitting (liftedExpPair z) (incl (e i)))
  · rintro ⟨f, hf⟩
    have hfField : AlgebraicIndependent ℚ (liftedExpPair z ∘ f) := by
      apply AlgebraicIndependent.of_comp (generatedField z).val
      simpa [Function.comp_def] using hf
    exact hfField.cardinalMk_le_trdeg

theorem bound_iff_exists_injective_algebraicIndependent_subfamily {n : ℕ}
    (z : Fin n → ℂ) :
    Bound z ↔ ∃ f : Fin n → Fin n ⊕ Fin n,
      Injective f ∧ AlgebraicIndependent ℚ (expPair z ∘ f) := by
  rw [bound_iff_exists_algebraicIndependent_subfamily]
  apply exists_congr
  intro f
  constructor
  · intro hf
    exact ⟨hf.injective.of_comp, hf⟩
  · exact And.right

/-- An equivalent finite-selection formulation of the full conjecture. -/
theorem conjecture_iff_exists_algebraicIndependent_subfamily :
    Conjecture ↔ ∀ (n : ℕ) (z : Fin n → ℂ), LinearIndependent ℚ z →
      ∃ f : Fin n → Fin n ⊕ Fin n,
        AlgebraicIndependent ℚ (expPair z ∘ f) := by
  constructor
  · intro h n z hz
    exact (bound_iff_exists_algebraicIndependent_subfamily z).mp (h n z hz)
  · intro h n z hz
    exact (bound_iff_exists_algebraicIndependent_subfamily z).mpr (h n z hz)

end

end Schanuel
